#!/usr/bin/env python3

text = '''
WELCOME.
WELCOME PILGRIM TO THE GREAT JOVRNEY TOWARD THE END OF ALL THNGS.
IT IS NOT AN EASY TRIP BVT MEOA OTHAEE WHO EAVIOE AEHPB TSIA WEODNG DAE VT D OHHTHAGAEOL OEEOTH.
RJRL AEH IHG BRF VFDR EAIVD BOE JAET TA APR HOYVIAGPTH BAET SOEMPTHMNG EOMSR AOEAOLCDCO IEVM YCLSEAPNV PBVE ERRTHJANVI INN PBVE BXLAEOJ.
VCFAEMIOOLJ IEV OEYCL HDVCEBOR NOE RNN OB SORG
'''

import string
text = ''.join([ i for i in text if i in string.ascii_uppercase ])
print(text)

print(len('WELCOMEWELCOMEPILGRIMTOTHEGREATJOVRNEYTOWARDTHEENDOFALLTHNGSITISNOTANEASYTRIPBVT'))
